name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.17', '1.18']
    name: Go ${{ matrix.go }} run
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          cd orders
          export PATH=${PATH}:`go env GOPATH`/bin
          make install_revive

      - name: Run orders make ci
        run: |
          cd orders
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -t .
          make ci
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make verify

      - name: Run customers make ci
        run: |
          cd customers
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -t .
          make ci
          git status
          git diff > diff.log
          cat diff.log
          git clean -fd
          git reset --hard
          make verify
